package layout

var KeyboardWeights = Weights{
	// Craft priority: 5 essential, 3 very important, 2 regular, 1 occasional,
	// 0.5 rare, 0 ignored. Unlisted crafts default to 1.
	Crafts: map[string]float64{
		"block.minecraft.white_bed":      5,
		"block.minecraft.respawn_anchor": 5,
		"item.minecraft.bow":             5,
		"item.minecraft.golden_pickaxe":  5,
		"item.minecraft.iron_axe":        4,
		"item.minecraft.stone_axe":       4,
		"item.minecraft.iron_sword":      4,
		"item.minecraft.stone_sword":     4,
		"item.minecraft.gold_ingot":      3,
		"item.minecraft.iron_ingot":      3,
		"block.minecraft.white_wool":     3,
		"block.minecraft.glowstone":      3,
		"block.minecraft.nether_bricks":  3,
		"item.minecraft.stick":           3,
		"item.minecraft.golden_carrot":   2,
		"item.minecraft.golden_helmet":   2,
		"item.minecraft.flint_and_steel": 2,
		"item.minecraft.bread":           2,
		"item.minecraft.iron_pickaxe":    2,
		"item.minecraft.stone_hoe":       2,
		"item.minecraft.blaze_powder":    1,
		"item.minecraft.ender_eye":       1,
		"item.minecraft.bucket":          1,
		"item.minecraft.diamond_sword":   0.5,
		"item.minecraft.stone_shovel":    0.5,
		"item.minecraft.oak_boat":        0.5,
	},
	Keys: map[string]KeyWeight{
		// higher weighting = harder to press
		"Space": {Effort: 1, Finger: "thumb"},
		"A":     {Effort: 1, Finger: "pinky"},
		"S":     {Effort: 1.2, Finger: "middle"},
		"D":     {Effort: 1, Finger: "index"},
		"W":     {Effort: 1, Finger: "middle"},
		"Q":     {Effort: 1.4, Finger: "ring"},
		"E":     {Effort: 1.5, Finger: "index"},
		"R":     {Effort: 1.6, Finger: "index"},
		"F":     {Effort: 1.5, Finger: "index"},
		"G":     {Effort: 2.5, Finger: "index"},
		"Z":     {Effort: 2, Finger: "ring"},
		"X":     {Effort: 2, Finger: "middle"},
		"C":     {Effort: 1.5, Finger: "index"},
		"V":     {Effort: 2.5, Finger: "index"},
		"1":     {Effort: 2.5, Finger: "ring"},
		"2":     {Effort: 1.8, Finger: "middle"},
		"3":     {Effort: 2, Finger: "index"},
		"4":     {Effort: 2, Finger: "index"},
	},
	SameFingerPenalty:        0.7,
	DefaultTransitionPenalty: 0.5,
	Transitions: map[Transition]float64{
		{From: "1", To: "2"}: 0.2,
		{From: "2", To: "1"}: 0.7,
		{From: "2", To: "3"}: 0.2,
		{From: "3", To: "2"}: 0.2,
		{From: "3", To: "4"}: 0.3,
		{From: "4", To: "3"}: 0.3,
		{From: "A", To: "S"}: 0.1,
		{From: "S", To: "A"}: 0.1,
		{From: "S", To: "D"}: 0.1,
		{From: "D", To: "S"}: 0.4,
		{From: "D", To: "F"}: 0.2,
		{From: "F", To: "D"}: 0.2,
		{From: "A", To: "W"}: 0.2,
		{From: "W", To: "A"}: 0.1,
		{From: "W", To: "D"}: 0.1,
		{From: "D", To: "W"}: 0.1,
		{From: "Q", To: "W"}: 0.3,
		{From: "W", To: "Q"}: 0.7,
		{From: "W", To: "E"}: 0.1,
		{From: "E", To: "W"}: 0.1,
		{From: "E", To: "R"}: 0.3,
		{From: "R", To: "E"}: 0.4,
	},
}
