package layout

var KeyboardWeights = Weights{
	Crafts:                   map[string]float64{"block.minecraft.glowstone": 3, "block.minecraft.nether_bricks": 3, "block.minecraft.respawn_anchor": 5, "block.minecraft.white_bed": 5, "block.minecraft.white_wool": 3, "item.minecraft.blaze_powder": 1, "item.minecraft.bow": 5, "item.minecraft.bread": 2, "item.minecraft.bucket": 1, "item.minecraft.diamond_sword": 0.5, "item.minecraft.ender_eye": 1, "item.minecraft.flint_and_steel": 2, "item.minecraft.gold_ingot": 3, "item.minecraft.golden_carrot": 2, "item.minecraft.golden_helmet": 2, "item.minecraft.golden_pickaxe": 5, "item.minecraft.iron_axe": 4, "item.minecraft.iron_ingot": 3, "item.minecraft.iron_pickaxe": 2, "item.minecraft.iron_sword": 4, "item.minecraft.oak_boat": 0.5, "item.minecraft.oak_planks": 0.5, "item.minecraft.stick": 3, "item.minecraft.stone_axe": 4, "item.minecraft.stone_hoe": 2, "item.minecraft.stone_shovel": 0.5, "item.minecraft.stone_sword": 4},
	PreferredLayers:          map[string]CraftLayer{"block.minecraft.glowstone": ShiftLayer, "block.minecraft.nether_bricks": ShiftLayer, "block.minecraft.respawn_anchor": NonShiftLayer, "block.minecraft.white_bed": ShiftLayer, "block.minecraft.white_wool": ShiftLayer, "item.minecraft.blaze_powder": ShiftLayer, "item.minecraft.bow": NonShiftLayer, "item.minecraft.bread": ShiftLayer, "item.minecraft.bucket": NonShiftLayer, "item.minecraft.diamond_sword": NonShiftLayer, "item.minecraft.ender_eye": ShiftLayer, "item.minecraft.flint_and_steel": AnyLayer, "item.minecraft.gold_ingot": ShiftLayer, "item.minecraft.golden_carrot": ShiftLayer, "item.minecraft.golden_helmet": AnyLayer, "item.minecraft.golden_pickaxe": ShiftLayer, "item.minecraft.iron_axe": NonShiftLayer, "item.minecraft.iron_ingot": ShiftLayer, "item.minecraft.iron_pickaxe": NonShiftLayer, "item.minecraft.iron_sword": NonShiftLayer, "item.minecraft.oak_boat": NonShiftLayer, "item.minecraft.stick": NonShiftLayer, "item.minecraft.stone_axe": NonShiftLayer, "item.minecraft.stone_hoe": ShiftLayer, "item.minecraft.stone_shovel": NonShiftLayer, "item.minecraft.stone_sword": NonShiftLayer},
	LayerPreferencePenalty:   5,
	LayerSwitchPenalty:       0.5,
	DistancePenalty:          1,
	FingerReusePenalty:       1,
	SameFingerPenalty:        1,
	DefaultTransitionPenalty: 0.5,
	PreferBothLayers:         map[rune]float64{110: 5},
	SearchEditing:            &SearchEditCosts{ShiftHome: 1, Backspace: 0.5},
	Groups: []CraftGroup{
		{Name: "fortress", Priority: 4, Crafts: []string{"item.minecraft.bow", "block.minecraft.respawn_anchor", "block.minecraft.white_bed", "item.minecraft.golden_pickaxe"}, Before: map[string][]string{}},
		{Name: "bastion", Priority: 3, Crafts: []string{"block.minecraft.white_bed", "item.minecraft.iron_ingot", "item.minecraft.iron_axe", "item.minecraft.iron_sword"}, Before: map[string][]string{"item.minecraft.iron_ingot": {"item.minecraft.iron_axe", "item.minecraft.iron_sword"}}},
		{Name: "bastion2", Priority: 3, Crafts: []string{"block.minecraft.white_bed", "item.minecraft.stone_axe", "item.minecraft.stone_sword"}, Before: map[string][]string{}},
		{Name: "2x2", Priority: 2, Crafts: []string{"block.minecraft.white_wool", "block.minecraft.nether_bricks", "block.minecraft.glowstone", "item.minecraft.stick"}, Before: map[string][]string{}},
		{Name: "chalice", Priority: 1, Crafts: []string{"item.minecraft.golden_helmet", "item.minecraft.golden_pickaxe"}, Before: map[string][]string{}},
		{Name: "eyes", Priority: 1, Crafts: []string{"item.minecraft.blaze_powder", "item.minecraft.ender_eye"}, Before: map[string][]string{}},
		{Name: "ow1", Priority: 1, Crafts: []string{"item.minecraft.stone_shovel", "item.minecraft.stone_axe"}, Before: map[string][]string{}},
		{Name: "ow2", Priority: 1, Crafts: []string{"item.minecraft.bucket", "item.minecraft.flint_and_steel", "item.minecraft.oak_boat"}, Before: map[string][]string{}},
		{Name: "ocean", Priority: 1, Crafts: []string{"item.minecraft.bread", "item.minecraft.iron_ingot"}, Before: map[string][]string{}},
	}, Keys: map[string]KeyWeight{
		"1":     {Effort: 2.5, Finger: "middle", X: 0, Y: 0},
		"2":     {Effort: 1.8, Finger: "middle", X: 1, Y: 0},
		"3":     {Effort: 2, Finger: "index", X: 2, Y: 0},
		"4":     {Effort: 2, Finger: "index", X: 3, Y: 0},
		"A":     {Effort: 1, Finger: "pinky", X: 0.25, Y: 2},
		"C":     {Effort: 1.5, Finger: "index", X: 2.75, Y: 3},
		"D":     {Effort: 1, Finger: "index", X: 2.25, Y: 2},
		"E":     {Effort: 1.5, Finger: "index", X: 2, Y: 1},
		"F":     {Effort: 1.5, Finger: "index", X: 3.25, Y: 2},
		"G":     {Effort: 2.5, Finger: "index", X: 4.25, Y: 2},
		"Q":     {Effort: 1.4, Finger: "ring", X: 0, Y: 1},
		"R":     {Effort: 1.6, Finger: "index", X: 3, Y: 1},
		"S":     {Effort: 1.2, Finger: "middle", X: 1.25, Y: 2},
		"Space": {Effort: 1, Finger: "thumb", X: 3, Y: 4},
		"V":     {Effort: 2.5, Finger: "index", X: 3.75, Y: 3},
		"W":     {Effort: 1, Finger: "middle", X: 1, Y: 1},
		"X":     {Effort: 2, Finger: "middle", X: 1.75, Y: 3},
		"Z":     {Effort: 2, Finger: "ring", X: 0.75, Y: 3},
	}, Transitions: map[Transition]float64{
		{From: "1", To: "2"}: 0.2,
		{From: "2", To: "1"}: 0.7,
		{From: "2", To: "3"}: 0.2,
		{From: "3", To: "2"}: 0.2,
		{From: "3", To: "4"}: 0.3,
		{From: "4", To: "3"}: 0.3,
		{From: "A", To: "S"}: 0.1,
		{From: "A", To: "W"}: 0.2,
		{From: "D", To: "F"}: 0.2,
		{From: "D", To: "S"}: 0.4,
		{From: "D", To: "W"}: 0.1,
		{From: "E", To: "R"}: 0.3,
		{From: "E", To: "W"}: 0.1,
		{From: "F", To: "D"}: 0.2,
		{From: "Q", To: "W"}: 0.3,
		{From: "R", To: "E"}: 0.4,
		{From: "S", To: "A"}: 0.1,
		{From: "S", To: "D"}: 0.1,
		{From: "W", To: "A"}: 0.1,
		{From: "W", To: "D"}: 0.1,
		{From: "W", To: "E"}: 0.1,
		{From: "W", To: "Q"}: 0.7,
	}}
var PreferredBindings = map[string]rune{}
var PreferredShiftBindings = map[string]rune{}
