// Package config defines the default language, inventory and crafting goals.
package config

const Language = "no_no"
const AllowGoodJunk = false

var Inventory = []string{"block.minecraft.gravel", "item.minecraft.string", "item.minecraft.nether_brick", "item.minecraft.diamond", "block.minecraft.white_wool", "item.minecraft.gunpowder", "item.minecraft.iron_nugget", "item.minecraft.coal", "block.minecraft.nether_bricks", "block.minecraft.sand", "item.minecraft.carrot", "block.minecraft.oak_slab", "item.minecraft.apple", "item.minecraft.ender_pearl", "item.minecraft.stick", "block.minecraft.obsidian", "item.minecraft.blaze_rod", "block.minecraft.crying_obsidian", "item.minecraft.leather", "block.minecraft.soul_sand", "item.minecraft.iron_ingot", "item.minecraft.gold_ingot", "item.minecraft.gold_nugget", "block.minecraft.glowstone", "block.minecraft.oak_log", "item.minecraft.glowstone_dust", "block.minecraft.dirt", "item.minecraft.flint", "item.minecraft.blaze_powder", "block.minecraft.cobblestone", "item.minecraft.wheat", "block.minecraft.blackstone", "block.minecraft.oak_planks", "block.minecraft.sandstone", "block.minecraft.mossy_stone_bricks"}
var Goals = []string{"block.minecraft.white_bed", "block.minecraft.respawn_anchor", "item.minecraft.bow", "item.minecraft.golden_pickaxe", "item.minecraft.iron_axe", "item.minecraft.stone_axe", "item.minecraft.iron_sword", "item.minecraft.stone_sword", "item.minecraft.gold_ingot", "item.minecraft.iron_ingot", "block.minecraft.white_wool", "block.minecraft.glowstone", "block.minecraft.nether_bricks", "item.minecraft.stick", "item.minecraft.golden_carrot", "item.minecraft.golden_helmet", "item.minecraft.flint_and_steel", "item.minecraft.bread", "item.minecraft.iron_pickaxe", "item.minecraft.blaze_powder", "item.minecraft.ender_eye", "item.minecraft.bucket", "item.minecraft.diamond_sword", "item.minecraft.stone_shovel", "item.minecraft.oak_boat", "block.minecraft.oak_planks"}
var PreferredSearches = map[string][]string{}
